Metrics/AbcSize:
  Enabled: true
  Max: 21

  #classにコメントすなければいけないのを開放。
Documentation:
    Enabled: false

AccessModifierIndentation:
    Enabled: false

ImplicitStringConcatenation:
    Enabled: false

IdenticalConditionalBranches:
    Enabled: false

MultilineTernaryOperator:
    Enabled: false

  #1行に記述できる文字数の制限を無効。
Metrics/LineLength:
  Enabled: false

  #日本語でのコメントを許可
AsciiComments:
  Enabled: false

#以下にはrubocopで検証したくないフォルダを指定する
AllCops:
  Exclude:
    - 'app/models/ckeditor/*'
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'config/database.yml'
    - 'config/*'
    - 'test/**/*'
    - 'node_modules/**/*'
    - 'config/unicorn/*'
    - 'lib/**/*'
