version: 2
jobs:
  docker:
    - image: circleci/ruby:2.6.3-node-browsers-legacy
      environment:
        RAILS_ENV: test
        POSTGRES_HOST: 127.0.0.1
    - image: circleci/postgres:9.6
      environment:
        POSTGRES_USER: <%= ENV.fetch('POSTGRES_USER') %>
        POSTGRES_PASSWPRD: <%= ENV.fetch('POSTGRES_PASSWORD') %>
        POSTGRES_DB: portfolio_test
  working_directory: ~/repo
  steps:
    - checkout
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
    - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
    - run: yarn install
    - save_cache:
        paths:
          - ./vendor/bundle
        key: v1-dependencies-{{ checksum "Gemfile.lock" }}
  rspec:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers-legacy
        environment:
          RAILS_ENV: test
          POSTGRES_HOST: 127.0.0.1
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: <%= ENV.fetch('POSTGRES_USER') %>
          POSTGRES_PASSWPRD: <%= ENV.fetch('POSTGRES_PASSWORD') %>
          POSTGRES_DB: portfolio_test
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: yarn install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      # Rspec
      - run:
          name: Rspec
          command: bundle exec rspec

workflows:
  version: 2
  rubocop_rspec:
    jobs:
      - rubocop
      - rspec:
