version: 2
jobs:
   build:
      docker:
        - image: circleci/ruby:2.6.3-node
      working_directory: ~/Portfolio
      
        environment:
          PGHOST: 127.0.0.1
          POSTGRES_USER: <%= ENV.fetch('POSTGRES_USER') %>
          POSTGRES_PASSWPRD: <%= ENV.fetch('POSTGRES_PASSWORD') %>
          POSTGRES_DB: portfolio_test
          RAILS_ENV: test
        steps:
          - checkout
          - run: npm run rspec
          - run: npm run deploy
