version: 2
jobs:
   build:
      parallelism: 3
      docker:
        - image: circleci/ruby:2.6.3-node

        working_directory: ~/Portfolio
        environment:
          PGHOST: 127.0.0.1
          POSTGRES_USER: <%= ENV.fetch('POSTGRES_USER') %>
          POSTGRES_PASSWPRD: <%= ENV.fetch('POSTGRES_PASSWORD') %>
          POSTGRES_DB: portfolio_test
          RAILS_ENV: test

    steps:
      - checkout

      # Restore bundle cache
      - type: cache-restore
        name: Restore bundle cache
        key: rails-demo-bundle-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle Install
          command: bundle install --path vendor/bundle

      # Store bundle cache
      - type: cache-save
        name: Save bundle cache
        key: rails-demo-bundle-{{ checksum 'Gemfile.lock' }}
        paths: vendor/bundle

      # Database setup
      - run:
          name: Database setup
          command: |
            bundle exec bin/rails db:create
            bundle exec rails db:migrate

      # Run rspec in parallel
      - type: shell
          command: |
            bundle exec rspec --profile 10 \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
