version: 2
jobs:
   build:
      docker:
        #アプリのバージョンを指定
        - image: circleci/ruby:2.6.3-node
          environment:
            - BUNDLER_VERSION: 2.0.2
            - RAILS_ENV: test
        - image: circleci/postgres:9.6-alpine
          environment:
            PGHOST: 127.0.0.1
            POSTGRES_USER: <%= ENV.fetch('POSTGRES_USER') %>
            POSTGRES_PASSWPRD: <%= ENV.fetch('POSTGRES_PASSWORD') %>
            POSTGRES_DB: portfolio_test
      working_directory: ~/Portfolio
      steps:
        - checkout
        
        - run: bundle exec rake db:create
        - run: bundle exec rake db:schema:load
        
        # rspec
        - run:
            name: run tests
            command: |
              mkdir /tmp/test-results
              TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
                circleci tests split --split-by=timings)"
