version: 2
jobs:
   build:
      docker:
        #アプリのバージョンを指定
        - image: circleci/ruby:2.6.3-node
          environment:
            - RAILS_ENV: test
        - image: circleci/postgres:9.6-alpine
          environment:
            PGHOST: 127.0.0.1
            POSTGRES_USER: <%= ENV.fetch('POSTGRES_USER') %>
            POSTGRES_PASSWPRD: <%= ENV.fetch('POSTGRES_PASSWORD') %>
            POSTGRES_DB: portfolio_test
      working_directory: ~/Portfolio
      steps:
        - checkout
        
        - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-

        - run:
            name: install dependencies
            command: |
              gem install bundler -v 2.0.2
              bundle install --jobs=4 --retry=3 --path vendor/bundle

        - save_cache:
          paths:
            - ./vendor/bundle
        
        - run: bundle exec rake db:create
        - run: bundle exec rake db:schema:load
        
        # rspec
        - run:
            name: run tests
            command: |
              mkdir /tmp/test-results
              TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
                circleci tests split --split-by=timings)"
