    default: &default
      adapter: postgresql
      encoding: unicode
      # 自身のpostgresqlに登録してあるユーザ名にする。
      username: ENV['POSTGRES_USER']
      password: ENV['POSTGRES_PASSWORD']      # docker-composeのPOSTGRES_PASSWORDと揃える。
      pool: 5
      host: db # docker-composeのサービス名にする。
      port: 5432

    development:
      <<: *default
      database: portfolio_development

    test:
      <<: *default
      database: portfolio_test
      
    production:
      <<: *default
      database: portfolio
      host: 13.115.179.212
