    default: &default
      adapter: postgresql
      encoding: unicode
      # 自身のpostgresqlに登録してあるユーザ名にする。
      username: postgres
      password: ${POSTGRES_PASSWORD}
      pool: 5
      host: db # docker-composeのサービス名にする。
      port: 5432

    development:
      <<: *default
      database: portfolio_development

    test:
      <<: *default
      database: portfolio_test
      #host: localhost
      host: db
      
    production:
      <<: *default
      database: portfolio
      host: localhost #AWSのhost名にする。
      port: 13.115.179.212
