    default: &default
      adapter: postgresql
      encoding: unicode
      host: localhost
      username: sahota0701nemoto  #記事内で後々出てきます。
      password: aaaa           #記事内で後々出てきます。
      pool: 5

    development:
      <<: *default
      database: portfolio_development

    test:
      <<: *default
      database: portfolio_test
      
    production:
      <<: *default
      database: portfolio
