    default: &default
      adapter: postgresql
      encoding: unicode
      # 自身のpostgresqlに登録してあるユーザ名にする。
      username: postgres
      password: aaaa     #${POSTGRES_PASSWORD}      # docker-composeのPOSTGRES_PASSWORDと揃える。
      pool: 5
      host: db # docker-composeのサービス名にする。
      port: 5432

    development:
      <<: *default
      database: portfolio_development
      host: db

    test:
      <<: *default
      database: portfolio_test
      #host: localhost
      host: <%= DATABASE_HOST %>
      #CircleCiの際はlocalhostにする必要があり、dockerを動かすにはdbにしなければいけない。
      #host: db

    production:
      <<: *default
      database: portfolio
      host: localhost
      #host: 3.114.69.77 #AWSのhost名にする。
