    default: &default
      adapter: postgresql
      encoding: unicode
      # 自身のpostgresqlに登録してあるユーザ名にする。
      username: postgres
      password: aaaa     #${POSTGRES_PASSWORD}      # docker-composeのPOSTGRES_PASSWORDと揃える。
      pool: 5
      host: db # docker-composeのサービス名にする。
      port: 5432

    development:
      <<: *default
      database: portfolio_development

    test:
      <<: *default
      database: portfolio_test
      #host: localhost CircleCiはlocalhostにする必要がある。
      host: db
      
    production:
      <<: *default
      database: portfolio
      host: localhost #AWSのhost名にする。
