    default: &default
      adapter: postgresql
      encoding: unicode
      # 自身のpostgresqlに登録してあるユーザ名にする。
      username: <%= ENV.fetch('POSTGRES_U') %>
      password: <%= ENV.fetch('POSTGRES_PASSWORD') %>      # docker-composeのPOSTGRES_PASSWORDと揃える。
      pool: 5
      host: <%= ENV.fetch('DATABASE_HOST') %> # docker-composeのサービス名にする。
      port: <%= ENV.fetch('DATABASE_PORT') { 5432 } %>

    development:
      <<: *default
      database: portfolio_development

    test:
      <<: *default
      database: portfolio_test
      
    production:
      <<: *default
      database: portfolio
